#!/usr/bin/env bash
# Infinite loop creates file with pid, catches signal, and removes file/exits

rmfile_n_terminate()
{
    rm -f /var/run/myscript.pid;
    exit
}
trap "echo 'Y U no love me?!'" SIGINT
trap "echo 'I hate the kill command'; rmfile_n_terminate" SIGTERM
trap "echo 'I hate the kill command'; rmfile_n_terminate" SIGQUIT


echo $$ >> /var/run/myscript.pid
while (true)
do
    echo 'To infinity and beyond'
    sleep 2
done
